version: "3.8"
services:
  mysql:
    image: mysql:latest
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_ROOT_USERNAME=YOUR_USERNAME
      - MYSQL_ROOT_PASSWORD=YOUR_PASSWORD
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  mysql:
